trainingInput:
  hyperparameters:
    maxTrials: 2
    maxParallelTrials: 1
    enableTrialEarlyStopping: True
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    params:
    - parameterName: batchsize
      type: DISCRETE
      discreteValues: [8, 16]
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.001
      maxValue: 0.01
      scaleType: UNIT_LOG_SCALE
    - parameterName: convrnn_filters
      type: DISCRETE
#      discreteValues: [8, 16, 24, 48, 64, 128]
      discreteValues: [8, 16]
    - parameterName: convrnn_layers
      type: DISCRETE
#      discreteValues: [1, 2, 3]
      discreteValues: [1]