trainingInput:
  hyperparameters:
    maxTrials: 3
    maxParallelTrials: 1
    enableTrialEarlyStopping: True
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    params:
    - parameterName: batchsize
      type: DISCRETE
      discreteValues: [8, 16, 24, 32]
    - parameterName: learning_rate
      type: DOUBLE
      minValue: 0.0001
      maxValue: 0.1
      scaleType: UNIT_LOG_SCALE
    - parameterName: convrnn_filters
      type: DISCRETE
      discreteValues: [8, 16, 24, 48, 64, 128, 256]
    - parameterName: experiment
      type: CATEGORICAL
      categoricalValues: [bands, bandswoblue, bands250m, bandsaux, evi2, indices, all]